# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import data_access_pb2 as data__access__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in data_access_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataAccessServiceStub(object):
    """Service definition exposing the data access methods.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetJobs = channel.unary_unary(
                '/dataaccess.DataAccessService/GetJobs',
                request_serializer=data__access__pb2.EmptyRequest.SerializeToString,
                response_deserializer=data__access__pb2.GetJobsResponse.FromString,
                _registered_method=True)
        self.GetReviews = channel.unary_unary(
                '/dataaccess.DataAccessService/GetReviews',
                request_serializer=data__access__pb2.EmptyRequest.SerializeToString,
                response_deserializer=data__access__pb2.GetReviewsResponse.FromString,
                _registered_method=True)
        self.GetAverageSalary = channel.unary_unary(
                '/dataaccess.DataAccessService/GetAverageSalary',
                request_serializer=data__access__pb2.AverageSalaryRequest.SerializeToString,
                response_deserializer=data__access__pb2.AverageSalaryResponse.FromString,
                _registered_method=True)


class DataAccessServiceServicer(object):
    """Service definition exposing the data access methods.
    """

    def GetJobs(self, request, context):
        """Returns all jobs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReviews(self, request, context):
        """Returns all reviews.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAverageSalary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataAccessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobs,
                    request_deserializer=data__access__pb2.EmptyRequest.FromString,
                    response_serializer=data__access__pb2.GetJobsResponse.SerializeToString,
            ),
            'GetReviews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReviews,
                    request_deserializer=data__access__pb2.EmptyRequest.FromString,
                    response_serializer=data__access__pb2.GetReviewsResponse.SerializeToString,
            ),
            'GetAverageSalary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAverageSalary,
                    request_deserializer=data__access__pb2.AverageSalaryRequest.FromString,
                    response_serializer=data__access__pb2.AverageSalaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataaccess.DataAccessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataaccess.DataAccessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataAccessService(object):
    """Service definition exposing the data access methods.
    """

    @staticmethod
    def GetJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataaccess.DataAccessService/GetJobs',
            data__access__pb2.EmptyRequest.SerializeToString,
            data__access__pb2.GetJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReviews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataaccess.DataAccessService/GetReviews',
            data__access__pb2.EmptyRequest.SerializeToString,
            data__access__pb2.GetReviewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAverageSalary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataaccess.DataAccessService/GetAverageSalary',
            data__access__pb2.AverageSalaryRequest.SerializeToString,
            data__access__pb2.AverageSalaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
