services:

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./datasets:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  data-access:
    build:
      context: ./microservices
      dockerfile: data_access/Dockerfile  # Build from Dockerfile
    container_name: data_access_service
    volumes:
      - ./datasets:/docker-entrypoint-initdb.d  # Mount init.db
    networks:
      - microservices
    ports:
      - "8083:50051"

  api-interface:
    build: 
      context: ./microservices
      dockerfile: api_interface/Dockerfile
    networks:
      - microservices
    ports:
      - "8082:8082"
    environment:
      JOBPOSTINSHOST: job-postings

  job-postings:
    build:
      context: ./microservices
      dockerfile: job_postings/Dockerfile
    networks:
      - microservices
    ports:
      - "8081:50051"
    environment:
      DATA_ACCESS_HOST: data-access

networks:
  microservices:
    driver: bridge