# job-postings-deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: job-postings-service
  namespace: job-app
  labels:
    app: job-postings
spec:
  ports:
  # Service Port - internal clients connect here
  - port: 50051
    # Target Port - references the *name* of the container port
    targetPort: grpc # Use a short, valid name (<= 15 chars)
    protocol: TCP
    name: grpc-svc-port # Name for the service port itself
  selector:
    app: job-postings # Selects pods with this label
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-postings-deployment
  namespace: job-app
  labels:
    app: job-postings
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: job-postings
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: job-postings
    spec:
      # No specific serviceAccountName needed unless accessing other GCP svcs
      containers:
      - name: job-postings
        # !!! ACTION REQUIRED: Replace with your actual image path !!!
        image: europe-west1-docker.pkg.dev/projectcloud-451415/cloudapiservice/job_postings:latest
        imagePullPolicy: Always
        ports:
          # Container port definition
        - containerPort: 50051 # The actual port your app listens on (from compose 8081:50051)
          name: grpc # The short name referenced by Service and Probes
        env:
          # Use K8s Service names for dependencies from compose env
          - name: DATA_ACCESS_HOST
            value: "data-access-service"
          - name: JOBREVIEWSHOST
            value: "job-reviews-service"
        # Add placeholder resources - ADJUST!
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        # Add placeholder probes - ADJUST! Use grpc_health_probe if possible
        livenessProbe:
          tcpSocket: { port: grpc } # Reference the named port
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket: { port: grpc }
          initialDelaySeconds: 5
          periodSeconds: 10
        startupProbe:
          tcpSocket: { port: grpc }
          failureThreshold: 30
          periodSeconds: 10