# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jobpostings.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'jobpostings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11jobpostings.proto\x12\x0bjobpostings\"l\n\x03Job\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x10\n\x08location\x18\x05 \x01(\t\x12\r\n\x05views\x18\x06 \x01(\x05\"%\n\x14\x41verageSalaryRequest\x12\r\n\x05title\x18\x01 \x01(\t\".\n\x15\x41verageSalaryResponse\x12\x15\n\raverageSalary\x18\x01 \x01(\x05\"/\n\x0ePostJobRequest\x12\x1d\n\x03job\x18\x01 \x01(\x0b\x32\x10.jobpostings.Job\"3\n\x0fPostJobResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb1\x01\n\x11JobPostingService\x12V\n\rAverageSalary\x12!.jobpostings.AverageSalaryRequest\x1a\".jobpostings.AverageSalaryResponse\x12\x44\n\x07PostJob\x12\x1b.jobpostings.PostJobRequest\x1a\x1c.jobpostings.PostJobResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jobpostings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOB']._serialized_start=34
  _globals['_JOB']._serialized_end=142
  _globals['_AVERAGESALARYREQUEST']._serialized_start=144
  _globals['_AVERAGESALARYREQUEST']._serialized_end=181
  _globals['_AVERAGESALARYRESPONSE']._serialized_start=183
  _globals['_AVERAGESALARYRESPONSE']._serialized_end=229
  _globals['_POSTJOBREQUEST']._serialized_start=231
  _globals['_POSTJOBREQUEST']._serialized_end=278
  _globals['_POSTJOBRESPONSE']._serialized_start=280
  _globals['_POSTJOBRESPONSE']._serialized_end=331
  _globals['_JOBPOSTINGSERVICE']._serialized_start=334
  _globals['_JOBPOSTINGSERVICE']._serialized_end=511
# @@protoc_insertion_point(module_scope)
