# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import jobpostings_pb2 as jobpostings__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in jobpostings_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JobPostingServiceStub(object):
    """-----------------------------
    Service Definition
    -----------------------------

    Service handling job posting functionalities.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AverageSalary = channel.unary_unary(
                '/jobpostings.JobPostingService/AverageSalary',
                request_serializer=jobpostings__pb2.AverageSalaryRequest.SerializeToString,
                response_deserializer=jobpostings__pb2.AverageSalaryResponse.FromString,
                _registered_method=True)
        self.PostJob = channel.unary_unary(
                '/jobpostings.JobPostingService/PostJob',
                request_serializer=jobpostings__pb2.PostJobRequest.SerializeToString,
                response_deserializer=jobpostings__pb2.PostJobResponse.FromString,
                _registered_method=True)


class JobPostingServiceServicer(object):
    """-----------------------------
    Service Definition
    -----------------------------

    Service handling job posting functionalities.
    """

    def AverageSalary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobPostingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AverageSalary': grpc.unary_unary_rpc_method_handler(
                    servicer.AverageSalary,
                    request_deserializer=jobpostings__pb2.AverageSalaryRequest.FromString,
                    response_serializer=jobpostings__pb2.AverageSalaryResponse.SerializeToString,
            ),
            'PostJob': grpc.unary_unary_rpc_method_handler(
                    servicer.PostJob,
                    request_deserializer=jobpostings__pb2.PostJobRequest.FromString,
                    response_serializer=jobpostings__pb2.PostJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jobpostings.JobPostingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jobpostings.JobPostingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobPostingService(object):
    """-----------------------------
    Service Definition
    -----------------------------

    Service handling job posting functionalities.
    """

    @staticmethod
    def AverageSalary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobpostings.JobPostingService/AverageSalary',
            jobpostings__pb2.AverageSalaryRequest.SerializeToString,
            jobpostings__pb2.AverageSalaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PostJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobpostings.JobPostingService/PostJob',
            jobpostings__pb2.PostJobRequest.SerializeToString,
            jobpostings__pb2.PostJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
