# datasets/secret-provider-class-postgres.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-gcp-secrets # Name of this SecretProviderClass resource
  namespace: job-app        # Must be in the same namespace as the Pod and the K8s Secret
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/1008860931487/secrets/postgres-database/versions/2"
        fileName: "database"      # This will be the key in the K8s Secret 'postgres-db-credentials'
      - resourceName: "projects/1008860931487/secrets/postgres-username/versions/2"
        fileName: "username"      # This will be the key in the K8s Secret 'postgres-db-credentials'
      - resourceName: "projects/1008860931487/secrets/postgres-password/versions/2"
        fileName: "password"      # This will be the key in the K8s Secret 'postgres-db-credentials'
    # The KSA 'postgres-ksa' (annotated for Workload Identity) running the pod
    # will be used by the CSI driver to authenticate with GCSM.
    # Alternatively, you could specify the GSA email here if not relying on pod's KSA:
    # gcpServiceAccount: "postgres-secrets-accessor@projectcloud-451415.iam.gserviceaccount.com"

  secretObjects:
  - secretName: postgres-db-credentials # Name of the Kubernetes Secret to create/update
    type: Opaque
    data:
    - key: database # Key in the Kubernetes Secret
      objectName: database # Corresponds to fileName above (which is the key in the GCSM secret data)
    - key: username
      objectName: username
    - key: password
      objectName: password
